### ISSUE TITLE
Core Module Missing dependency

### ISSUE THREAD

**Issue by aneesahmadweb** [di-zed/m2-wishlist-guest#1]
Hi, When i run setup:di:compile it shows this error 
 Impossible to process constructor argument Parameter #2 [ <required> DiZed\Core\Helper\CoreHelper $coreHelper ] of
  DiZed\WishlistGuest\Cron\RemoveWishlists class
Can you please share Core Module or remove the Dependency.?

**Comment by di-zed** [comment]
Hello, @aneesahmadweb! It's strange because if you installed it via composer, everything should be okay because the module is already mentioned in the depencies.
But if you want to have it separately, you can download it here: https://github.com/di-zed/m2-core
